### ISSUE TITLE
[JOSS Review] Installation

### ISSUE THREAD

**Issue by rmorgan10** [grant-m-s/AstronomicAL#10]
This issue is part of the JOSS review going on in https://github.com/openjournals/joss-reviews/issues/3635.

At present, the installation instructions are inaccurate. After cloning, users need to enter the command `cd astronomicAL` such that the environment creation command can access the `requirements.txt` file. Adding this command to the instructions will be sufficient to satisfy the JOSS installation specifications.

That being said, I think the better way to go about installation would be to make your package available on PyPI. The motivation here is to enable users to be able to use astronomicAL in any directory they are working in as opposed to having to move their work to the location of the cloned repository. This change is optional, but could make astronomicAL much more portable.

**Comment by grant-m-s** [comment]
I made the `cd astronomicAL` change.

> I think the better way to go about installation would be to make your package available on PyPI

This was something I was planning on doing after the JOSS submission.

Let me know if this issue is now closable.

**Comment by crhea93** [comment]
Hey there! 
I've followed the new installation instructions
``` git clone https://github.com/grant-m-s/AstronomicAL.git
    cd AstronomicAL
    conda create --name astronomical --file requirements.txt
    conda activate astronomical
```
but I get the following error:
```
remote: Enumerating objects: 1850, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 1850 (delta 8), reused 0 (delta 0), pack-reused 1833
Receiving objects: 100% (1850/1850), 61.24 MiB | 9.00 MiB/s, done.
Resolving deltas: 100% (1088/1088), done.
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - modal[version='>=0.4.1']
  - datashader==0.12.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Could not find conda environment: astronomical
You can list all discoverable environments with `conda info --envs`.
```

The last bit is of course because the environment wasn't properly created, but the conda install failed because it couldn't find those two packages: modal & datashader.

**Comment by rmorgan10** [comment]
One more suggestion for the installation: Can you please add pytest to the requirements.txt file? Currently I have to pip install into the astronomical environment to run the tests

**Comment by grant-m-s** [comment]
Its now been added to the req file.

**Comment by crhea93** [comment]
Great! Everything is working beautifully now!

**Comment by grant-m-s** [comment]
Awesome! Thanks for this.

I think this is now closable.
