### ISSUE TITLE
[JOSS Review] Paper

### ISSUE THREAD

**Issue by rmorgan10** [grant-m-s/AstronomicAL#9]
This issue is part of the JOSS review going on in https://github.com/openjournals/joss-reviews/issues/3635.

The paper is well written and does an excellent job of introducing astronomicAL. I think two aspects of the paper can be improved.

1. The state of the field discussion seems to be missing. Perhaps some examples where active learning has been applied would be helpful here. 

1. The statement of need section seems to list the features of astronomicAL as opposed to demonstrating why it is a needed piece of software. I'm aware that there is significant need for a tool like this, but I think that fact could be communicated better in the paper. For instance, when you add a more descriptive state of the field, that discussion will lend itself nicely to introducing the reason the field needs astronimcAL.

**Comment by grant-m-s** [comment]
Thanks again for the feedback.

This one will take me about a week to get an update through, as I already found it a challenge to get the word count down to what it is currently. Are there any parts of the paper that you feel are unnecessary?

**Comment by rmorgan10** [comment]
I think the length is a-ok, no need to trim further. I'm picturing an additional paragraph about the state of the field that concludes with something along the lines of "... and astronomicAL's goal is to satisfy these needs of the field." Then go into your current statement of need text which details the main functionalities. And I don't think one additional paragraph would hurt the overall length.

**Comment by rmorgan10** [comment]
By the way one additional thing (though completely optional) is to use a colorblind friendly colormap in Figure 3. I put a red-green colorblind filter on my screen and couldn't tell the difference between the red and green regions, so the gradient of the colormap was lost.

**Comment by grant-m-s** [comment]
I've pushed an updated paper (viewable on the main review issue). Let me know if that is what you had in mind.

**Comment by rmorgan10** [comment]
Your changes are exactly what I had in mind. Looks good to me! Go ahead and close this issue and we can reopen it if any of the other reviewers have paper comments.
